
// Del 1
'granska Xojo', 'undersök Guanmgon', 'inspektera SCU', 'bekräfta', 'studera CT-22', 'plocka upp HV-chip', 'analysera testare', 'skärskåda etiketter', 'frigör testare', 'hämta LV-chip', 'placera det i uttaget', 'infoga CT i facket', 'aktivera SCU', 'förflytta västerut', 'gå väster', 'utfråga Xojo om Mitachron', 'dofta på Koffee', 'förtär det', 'gå väster', 'betrakta mig själv', 'informera Xojo om anställningsstoppet', 'granska kontraktet', 'studera meritförteckningen', 'fråga ut Xojo om Kowtuan', 'utforska ChipTechNo med Xojo', 'diskutera Magnxi med Xojo', 'be Xojo berätta om hissen', 'observera klockan', 'konsultera Xojo angående kraftverket', 'be Xojo förklara Guanmgon', 'öppna dörren', 'återuppta diskussionen om hissen', 'upprepa', 'titta uppåt mot taket', 'inspektera panelen', 'demontera panelen', 'använd Xojo som stege', 'forcera panelen', 'klättra uppåt', 'undersök kabeln', 'ryck i den', 'granska utsprånget', 'forcera dörren', 'studera mekanismen', 'applicera meritförteckningen på mekanismen', 'ta en närmare titt på panelen', 'införskaffa den', 'applicera den på mekanismen', 'bända upp dörren', 'gå österut', 'återuppta diskussionen om hissen', 'fortsätt österut', 'gå öster igen', 'förflytta norrut', 'gå norr igen', 'fortsätt norrut', 'granska bron', 'studera huvudbron', 'undersök ravinen', 'fråga Xojo om brokonstruktionen', 'upprepa', 'fortsätt fråga', 'insistera', 'gå norrut', 'fortsätt norrut', 'be Xojo elaborera om bron', 'fortsätt norrut', 'gå norr igen', 'utforska bron ytterligare med Xojo', 'klättra uppåt', 'be om Xojos åsikt om bron', 'bege dig nordöst', 'stig in', 'granska Magnxi', 'studera hatten', 'undersök uniformen', 'inled konversation med Magnxi'

// Del 2
'gå norrut', 'förflytta österut', 'bege dig söderut', 'granska kvinnan', 'undersök stället', 'studera mortelstöten', 'analysera toxicola', 'inspektera locktheon', 'observera Belker', 'bekräfta', 'instäm', 'studera anteckningen', 'godta erbjudandet', 'gå norrut', 'bege dig västerut', 'förflytta söderut', 'gå väster', 'fortsätt söderut', 'gå söder igen', 'bege dig österut', 'förflytta norrut', 'gå norr igen', 'läs skylten', 'granska Aaron', 'studera Erin', 'undersök lådan', 'inspektera kontakten', 'analysera bordet', 'sök under bordet', 'granska kablarna', 'inventera', 'undersök axelväskan', 'granska plånboken', 'öppna plånboken', 'studera kreditkortet', 'inspektera alumnkortet', 'analysera körkortet', 'förvara plånboken i fickan', 'gå söderut', 'fortsätt söderut', 'bege dig västerut', 'förflytta norrut', 'observera arbetaren', 'granska utrustningen', 'gå västerut', 'fortsätt västerut', 'gå väster igen', 'bege dig söderut', 'undersök montern', 'studera anteckningsboken', 'granska motorn', 'gå nedåt', 'förflytta norrut', 'inspektera miniräknaren', 'ta upp den', 'granska mappen', 'plocka upp den', 'läs innehållet', 'undersök bänken', 'studera experimentet', 'aktivera den gröna knappen', 'granska plattformen', 'undersök hyllorna', 'hämta generatorn', 'inspektera den', 'studera vredet', 'granska kontakten', 'ta med oscilloskopet', 'undersök proben', 'granska bollen', 'plocka upp kameran', 'studera kabeln', 'dra i den', 'läs etiketten'

// Del 3
'gå söderut', 'bege dig västerut', 'gå nedåt', 'förflytta norrut', 'undersök ledningarna', 'granska den blå kabeln', 'gå söderut', 'bege dig österut', 'inspektera möblerna', 'undersök lådorna', 'granska träet', 'förflytta träet', 'gå norrut', 'bege dig västerut', 'undersök hålet', 'granska kabeln', 'gå västerut', 'studera kabeln', 'förflytta söderut', 'inspektera kabeln', 'gå västerut', 'analysera kabeln', 'granska dörren', 'dölj mig i nischen', 'mata in 57212 på dörren', 'gå västerut', 'undersök den blå kabeln', 'bege dig österut', 'fortsätt österut', 'förflytta norrut', 'gå österut', 'fortsätt österut', 'gå öster igen', 'bege dig österut', 'förflytta norrut', 'gå österut', 'presentera mig', 'avböj', 'fråga ut Plisnik om råttorna', 'utforska honom', 'granska pärmen', 'undersök pärmen', 'fråga om NIC', 'utforska analysatorn', 'gå uppåt'

// Del 4
'bege dig nordväst', 'granska stället', 'plocka upp tidningen', 'undersök djuret', 'fånga råttan', 'studera expediten', 'inhandla tidningen', 'ta den', 'läs innehållet', 'placera råttan på disken', 'bekräfta', 'öppna plånboken', 'överlämna kreditkortet till expediten', 'förvara kreditkortet i plånboken', 'granska kvittot', 'stoppa plånboken i fickan', 'packa ner råttan, kvittot och tidningen i väskan', 'gå sydöst', 'bege dig västerut', 'förflytta norrut', 'gå österut', 'undersök bilen', 'granska fjärrkontrollen', 'förvara bilen och fjärrkontrollen i väskan', 'gå västerut', 'bege dig söderut', 'förflytta österut', 'gå norrut', 'bege dig nordöst', 'studera memot', 'läs det rosa kortet', 'granska det gula kortet', 'undersök det blå kortet', 'studera det gröna kortet', 'packa ner allt från disken i väskan', 'gå sydväst', 'bege dig söderut', 'fortsätt söderut', 'förflytta österut', 'gå norrut', 'fortsätt norrut'

// Del 5
'undersök datorn', 'anslut generatorn till lådan', 'starta generatorn', 'hämta oscilloskopet', 'aktivera oscilloskopet', 'mät låd-kontakten med oscilloskopet', 'ta med generatorn och oscilloskopet', 'gå söderut', 'fortsätt söderut', 'bege dig österut', 'granska berget', 'bestiga berget', 'undersök behållaren', 'gå söderut', 'granska Positron', 'studera instruktionskortet', 'undersök serviceluckan', 'öppna den', 'gå norrut', 'klättra uppåt', 'förflytta norrut', 'studera klottret', 'gå norrut', 'läs skylten', 'granska datorn', 'fråga ut Erin om stacken', 'diskutera EE med Erin', 'utforska qubits med Erin', 'fråga Erin om Jay', 'knacka på dörr 39', 'lokalisera biblioteket på kartan', 'gå söderut', 'fortsätt söderut', 'gå nedåt', 'bege dig västerut', 'fortsätt västerut', 'hitta biblioteket på kartan', 'förflytta norrut', 'gå västerut', 'fortsätt västerut', 'gå väster igen', 'bege dig västerut', 'granska receptionisten', 'undersök läroboken', 'fråga om läroboken', 'upprepa', 'insistera', 'ta fram plånboken', 'visa upp alumnkortet för honom', 'förvara plånboken i fickan', 'studera katalogen', 'granska hissen', 'aktivera uppåtknappen', 'gå norrut', 'tryck på knapp 3', 'vänta', 'vänta ytterligare', 'gå söderut', 'sök efter Morgen', 'läs informationen', 'leta upp Townsend', 'studera texten', 'aktivera uppåtknappen', 'gå norrut', 'tryck på knapp 6', 'vänta', 'vänta igen', 'gå söderut', 'hitta Blomner', 'läs om det', 'sök efter 70:11c', 'studera innehållet', 'aktivera nedåtknappen', 'gå norrut', 'tryck på knapp 2', 'vänta', 'vänta ytterligare', 'gå söderut', 'leta upp XLVI-3', 'läs rapporten', 'granska rapporten', 'aktivera uppåtknappen', 'gå norrut', 'tryck på knapp 6', 'vänta', 'vänta igen', 'gå söderut', 'hitta 73:9a', 'studera texten', 'aktivera nedåtknappen', 'gå norrut', 'tryck på knapp 1', 'vänta', 'vänta ytterligare', 'gå söderut', 'bege dig österut'

// Del 6
'gå söderut', 'förflytta nedåt', 'bege dig västerut', 'gå nedåt', 'förflytta österut', 'gå norrut', 'bege dig österut', 'fortsätt österut', 'gå norrut', 'plocka upp bilen', 'placera råttan på bilen', 'släpp bilen', 'undersök bilen', 'ta fjärrkontrollen', 'granska den', 'studera joysticken', 'manövrera joysticken österut', 'gå österut', 'bekräfta', 'be arbetaren om analysatorn', 'hämta bilen', 'ta pärmen', 'studera den', 'leta upp 3349-2016 i pärmen', 'sök efter 3312-8622 i pärmen', 'plocka upp det smutsiga papperet', 'läs innehållet', 'gå västerut', 'bege dig söderut', 'fortsätt västerut', 'gå väster igen', 'fortsätt västerut', 'gå väster ytterligare', 'förflytta söderut', 'bege dig västerut', 'gå väster igen', 'granska lådan', 'koppla in analysatorn i uttaget', 'mata in 09C0A848D6 på analysatorn', 'gå österut', 'fortsätt österut', 'förflytta norrut', 'gå norr igen', 'fortsätt norrut', 'bege dig österut', 'gå öster igen', 'undersök säkringsskåpet', 'granska DEI', 'gå österut', 'bege dig söderut', 'förflytta österut', 'klättra uppåt', 'gå söderut', 'bege dig österut', 'fortsätt österut'

// Del 7
'gå sydväst', 'bege dig österut', 'granska kycklingarna', 'undersök anteckningsboken', 'studera innehållet', 'inspektera kartongen', 'kliv in i den', 'läs skylten', 'förvara allt utom dräkten i väskan', 'släpp väskan', 'klä på dig dräkten', 'aktivera spaken', 'kliv ut', 'fråga ut kycklingarna om Scott', 'utforska Positron med Scott', 'undersök vad som är fel', 'erbjud dig att reparera den', 'bekräfta', 'redogör för Stamers stack', 'betala för reparationerna', 'gå in', 'aktivera spaken', 'ta av dig dräkten', 'häng upp dräkten på kroken', 'hämta väskan', 'gå ut', 'bege dig västerut', 'förflytta norrut', 'gå söderut', 'lås upp dörren', 'öppna den', 'ta säcken', 'granska den', 'undersök innehållet', 'studera kortet', 'mät kortet med oscilloskopet', 'starta spelet', 'mät kortet igen med oscilloskopet', 'leta upp videoförstärkare i manualen', 'mät videoförstärkaren med oscilloskopet', 'hitta 1a80 i manualen', 'mät 1a80 med oscilloskopet',