# TADS 3 makefile för spelet Ruiner

-nodef
#-we
-D LANGUAGE=sv_se
-D MESSAGESTYLE=neu
-D __DEBUG
-Fy obj
-Fo obj
-v
-D
-d
-FI /usr/local/share/frobtads/tads3/include
-Fs /usr/local/share/frobtads/tads3/lib
-I ../../extensions
-o ruiner.t3

##sources

-lib system.tl
-lib adv3/adv3
  -x footnote
  -x hintsys

-source dynfunc
-source ../../extensions/tests2
-source ../../extensions/cquotes

-source ruiner

-res
GameInfo.txt
