# TADS 3 makefile för spelet Ruiner

-nodef
#-we
-D LANGUAGE=sv_se
-D MESSAGESTYLE=neu
-D __DEBUG

-D DEBUG__

-Fy obj
-Fo obj
-v
-d
-FI /usr/local/share/frobtads/tads3/include
-Fs /usr/local/share/frobtads/tads3/lib
-o ruiner-dbg.t3

##sources

-lib system.tl
-lib adv3/adv3
  -x footnote
  -x hintsys

-source dynfunc
-source tests2 
-source ../../lib/eval
-source reflect


-source cquotes
-source ruiner

-res
GameInfo.txt
