# Makefile 

-nodef
-D LANGUAGE=sv_se
-D MESSAGESTYLE=neu
-D __DEBUG
-Fy obj
-Fo obj
-v
-D
-d
-FI /usr/local/share/frobtads/tads3/include
-Fs /usr/local/share/frobtads/tads3/lib
-o tester.t3

##sources
-lib system.tl
-lib adv3/adv3
-source dynfunc
-source ../extensions/tests2

# TESTER 
-source testunit.t

-source present-tense
#-source past-tense
#-source satsdelar
#-source initialize-tests
#-source additional-tests

#-source parser-tests

